export const API_URL_USERS = 'http://localhost:3001/api/v1/users' //'https://khem-library.herokuapp.com/api/v1/users'
export const API_URL_BOOKS = 'http://localhost:3001/api/v1/books' //'https://khem-library.herokuapp.com/api/v1/books'
export const API_URL_LOGIN = 'http://localhost:3001/api/v1/login' //'https://khem-library.herokuapp.com/api/v1/login'
export const API_URL_GOOGLE_LOGIN = 'http://localhost:3001/api/v1/auth/google/'
export const API_URL_AUTHORS = 'http://localhost:3001/api/v1/authors' //'https://khem-library.herokuapp.com/api/v1/authors'
export const API_URL_LOANS = 'http://localhost:3001/api/v1/loans' //'https://khem-library.herokuapp.com/api/v1/loans'
