name: Nodejs project and deploying to Netlify
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
            node-version: 12.x

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get yarn cache dir
        id: yarn-cache-dir
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - name: Setup cache
        uses: actions/cache@v1
        with:
            key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
            path: ${{ steps.yarn-cache-dir.outputs.dir }}
            restore-keys: |
              ${{ runner.os }}-node-
              ${{ runner.os }}-

      - name: Install node -modules
        run: yarn install --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Testing
        run: CI=true yarn test

      - name: Building
        run: yarn build
  
      - name: Deploy to Netlify
        uses: netlify/actions/cli@master
        with:
          publish-dir: './public'
          production-branch: master
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
       
 